---
- name: Install Bat
  become: true
  package:
    name: [ bat ]

- name: Ensure ~/.local/bin directory exists and create a symlink for batcat (work around)
  block:
    - name: Create the ~/.local/bin directory
      file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Create a symlink from /usr/bin/batcat to ~/.local/bin/bat
      file:
        src: /usr/bin/batcat
        dest: "{{ ansible_env.HOME }}/.local/bin/bat"
        state: link

- name: Set alias for fzf with bat preview
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'alias fzfp="fzf --preview \\"bat --color=always --style=numbers --line-range=:500 {}\\""'
    create: yes
