---
- name: Bat installation and configuration
  become: true
  become_user: mythi
  vars:
    mythi_home: "/home/mythi"
  block:
  - name: Install the .deb package for from the internet (github)
    become: true
    become_user: root
    ansible.builtin.apt:
      deb: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat_0.24.0_amd64.deb

  - name: Set alias for fzf with bat preview
    lineinfile:
      path: "{{ mythi_home }}/.bashrc"
      line: 'alias fzfp="fzf --preview \"bat --color=always --style=numbers --line-range=:500 {}\""'
      create: yes
      owner: mythi
      group: mythi

