- name: Install JetBrains Mono
  block:
    - name: Download font
      get_url:
        url: https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
        dest: "{{ lookup('env', 'HOME') }}"
    - name: Unzip font
      unarchive:
        src: "{{ lookup('env', 'HOME') }}/JetBrainsMono-2.304.zip"
        dest: "{{ lookup('env', 'HOME') }}/local/share/fonts"
    - name: Clear font cache
      shell: "fc-cache -f -v"
