---
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
    clone: yes
    version: master
    depth: 1
- name: Install fzf
  shell: "$HOME/.fzf/install" 
  become: true
  become_user: mythi
