- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "hashem.olayano@gmail.com"
- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "hashem78"
