- name: Install fnm
  shell: curl -fsSL https://fnm.vercel.app/install | bash

- name: Set default node version to 20
  environment: 
    PATH: "{{ lookup('env', 'HOME') }}/.local/share/fnm"
  shell: "fnm install 20 && fnm default 20"
