- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
- name: Start ssh-agent in the backgroud
  shell: eval "$(ssh-agent -s)"
- name: Add key to ssh-agent
  shell: "ssh-add {{ desk_key }}"
