- name: Ensure .ssh directory exists.
  vars:
    source_key: "./.ssh/personal-mythi"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/personal-mythi"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
